Metrics/BlockLength:
  Exclude:
    - config/routes.rb
    - spec/support/**/*
    - db/schema.rb
  ExcludedMethods:
    - describe
    - context
    - factory
    - it

Metrics/LineLength:
  Max: 120

Style/FrozenStringLiteralComment:
  Enabled: false

Documentation:
  Enabled: false